#
# Module manifest for module 'Juriba.AppR'
#
# Generated by: Juriba
#
# Generated on: 03/20/2026
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'Juriba.AppR.psm1'

    # Version number of this module.
    ModuleVersion     = '0.3.7'

    # Supported PSEditions
    CompatiblePSEditions = @('Core')

    # ID used to uniquely identify this module
    GUID              = 'a7e3f8b1-4d2c-4f6a-9e1b-3c5d7f8a2b4e'

    # Author of this module
    Author            = 'Juriba'

    # Company or vendor of this module
    CompanyName       = 'Juriba'

    # Copyright statement for this module
    Copyright         = '(c) Juriba. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'PowerShell module to interact with Juriba App Readiness (AppR). Provides cmdlets for managing applications, packaging, smoke testing, quality review, and publishing to distribution systems such as Intune and MECM.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '7.1'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        # Connection & Authentication
        "Connect-JuribaAppR",
        "Disconnect-JuribaAppR",
        "Get-JuribaAppRSession",
        "Set-JuribaAppRAPIKey",
        "Get-JuribaAppRAboutInfo",

        # Query - Applications
        "Get-JuribaAppRApplication",
        "Get-JuribaAppRApplicationList",
        "Get-JuribaAppRApplicationStatus",
        "Get-JuribaAppRApplicationPackage",
        "Get-JuribaAppRApplicationPackageDetail",
        "Get-JuribaAppRApplicationEvent",

        # Query - Users
        "Get-JuribaAppRUser",

        # Query - Quality Review
        "Get-JuribaAppRQualityReview",

        # Settings
        "Get-JuribaAppRDefaultSetting",
        "Get-JuribaAppRCommandSuggestion",

        # Upload / Create / Monitor Applications
        "Send-JuribaAppRSetupFile",
        "New-JuribaAppRApplication",
        "Get-JuribaAppRApplicationCreationState",
        "Watch-JuribaAppRApplicationCreation",
        "Watch-JuribaAppRApplicationStatus",
        "Set-JuribaAppRApplication",
        "Set-JuribaAppRApplicationOwner",
        "Set-JuribaAppRApplicationCommandLine",
        "Remove-JuribaAppRApplication",

        # Testing
        "Get-JuribaAppRVMGroup",
        "Get-JuribaAppRTestApplication",
        "Start-JuribaAppRSmokeTest",
        "Stop-JuribaAppRSmokeTest",
        "Get-JuribaAppRTestResult",
        "Get-JuribaAppRTestStat",

        # Publishing
        "Get-JuribaAppRIntegrationConnector",
        "Get-JuribaAppRPublishingProperty",
        "Invoke-JuribaAppRPublishIntune",
        "Invoke-JuribaAppRPublishMECM",
        "Invoke-JuribaAppRPublishGeneric",

        # MECM (SCCM) Import + Provider Configuration
        "Get-JuribaAppRMECMProvider",
        "Get-JuribaAppRMECMImportAvailability",
        "Get-JuribaAppRMECMImportEvent",
        "Get-JuribaAppRMECMScanList",
        "Start-JuribaAppRMECMScan",
        "Start-JuribaAppRMECMImport",
        "Set-JuribaAppRMECMProviderUniqueness",
        "Remove-JuribaAppRMECMProvider",

        # Knowledge Base
        "Search-JuribaAppRKnowledgeBase",

        # Generic Integration (v1 API - refactored from original scripts)
        "Get-JuribaAppRGenericIntegration",
        "Get-JuribaAppRGenericIntegrationPublishing",
        "Get-JuribaAppRGenericIntegrationPrerequisite",
        "Get-JuribaAppRGenericIntegrationProperty",
        "Get-JuribaAppRGenericIntegrationSource",
        "Add-JuribaAppRGenericIntegrationLog",
        "Update-JuribaAppRGenericIntegrationPublishingState"
    )

    # Cmdlets to export from this module
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module
    AliasesToExport   = @(
        "Connect-AppR",
        "Disconnect-AppR",
        # Backward-compatibility aliases for plural→singular renames (v0.1.x):
        "Get-JuribaAppRDefaultSettings",
        "Get-JuribaAppRTestStats"
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('Juriba', 'AppReadiness', 'AppR', 'Packaging', 'Intune', 'MECM', 'SmokeTest')

            # A URL to the license for this module.
            LicenseUri = 'https://raw.githubusercontent.com/juribalimited/powershell-module-appr/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/juribalimited/powershell-module-appr'

            # A URL to an icon representing this module.
            IconUri    = 'https://raw.githubusercontent.com/juribalimited/powershell-module-appr/main/resources/juriba_logo.jpeg'

            # ReleaseNotes of this module
            ReleaseNotes = '0.3.7 - Examples/Test-WatchAndPublishIntune.ps1 hardened for customer-facing demos. Picks up the Resolve-AppRId and Resolve-AppRName helpers plus the Lite-to-V2 application-list fallback from Import-MECMAppAndSmokeTest.ps1, so the watcher works on AppR / AppM versions where the lite endpoint returns a different id shape or falls through to SPA HTML for partial-admin API keys. Replaces the mandatory plain-text -APIKey parameter with the secure-by-default pattern used elsewhere in the module: re-uses an existing Connect-JuribaAppR session, then prefers -SecretName (SecretManagement), -SecureAPIKey, an interactive Read-Host -AsSecureString prompt, and finally -APIKey (with a deprecation warning). Adds -Confirm:$false to Invoke-JuribaAppRPublishIntune so the watcher does not block on confirmation prompts in unattended runs. Wraps the polling body in try/catch so a transient API error does not terminate the watcher, and wraps the whole loop in try/finally so a Ctrl+C cleanly disconnects sessions the script established. Module import is now robust to both PSGallery-installed and dev-clone layouts. -Instance accepts -InstanceUrl as an alias for backward compatibility with earlier invocations of the script.

0.3.6 - Search-JuribaAppRKnowledgeBase now speaks the v6 OData contract on /api/kb/application (?$filter=...&$top=...) and unwraps the {paginationMetadata,data:[...]} envelope, with automatic fallback to the legacy ?search=<term> shape so v5 instances keep working. Auto-fallback to UDA removed; -UseUDA stays as an explicit-only escape hatch. Per-app /version/sources path unchanged.

0.3.5 - Add Start-JuribaAppRMECMScan, mirroring the AppR admin UI''s "Start scan" button on the Scan & Import page. POSTs to /api/integration/{providerId}/scan with an empty body; returns immediately while the scan runs asynchronously on the server. Closes the gap for callers automating "create CM app -> import to AppR -> smoke test" end-to-end: when the autoscheduler''s cadence is too slow, kick a scan from PowerShell instead of waiting. Accepts pipeline input by property name so Get-JuribaAppRMECMProvider | Where ... | Start-JuribaAppRMECMScan works. Track scan progress with Get-JuribaAppRMECMScanList (new rows appear with recent createdAt) or the AppR UI''s progress banner.

0.3.4 - Customer-driven fixes from a real-MECM v4 AppM environment. Examples/Import-MECMAppAndSmokeTest.ps1: (1) The pre-import snapshot used Select-Object -ExpandProperty id against Get-JuribaAppRApplicationList -AllUsers -Lite, which throws "Property ''id'' cannot be found" on AppR versions that surface the application id under appId or applicationId instead. The script''s own trailing fallback chain already acknowledged the schema variance; this consolidates the snapshot, post-import diff, display strings, and final id resolution onto one Resolve-AppRId helper that tries id / appId / applicationId / nested basic.id. (2) The "no scan-list row matched ... with an importable status" error now distinguishes a true name-lookup miss from the much more common case of AppR''s MECM auto-import having already pulled the CM app (scan-list row in status 2 = already imported, 4 or 5 = in flight). The status-excluded branch reports the observed statuses, explains what they mean, and points the caller at -SkipImport. (3) On API keys with partial admin scope, the Lite all-users application list endpoint can return 200 OK with text/html (the SPA index) instead of JSON. (4) Adds Resolve-AppRName helper for V2 shape compatibility. Start-JuribaAppRSmokeTest: (5) Maps ''nonStd'' to its integer enum value 10 before sending to fix 400 ''CantFindTheAppInformation''.

0.3.3 - End-to-end MECM import + smoke-test verified on sandbox.appr.juriba.app: Get-JuribaAppRMECMScanList | Start-JuribaAppRMECMImport produces a new AppR app with the matching scan-list row, and Start-JuribaAppRSmokeTest succeeds against it once availPackages.<type> flips true. Two improvements driven by that validation: Get-JuribaAppRUser -Me now merges /api/apm/user/whoAmI (numeric id) into /api/apm/user/whoAmI/full (profile body) so callers can resolve their own user id without two requests — needed for Set-JuribaAppRApplicationOwner. Examples/Import-MECMAppAndSmokeTest.ps1 now (a) calls Set-JuribaAppRApplicationOwner after import so the AppR UI''s smoke-test "Created By" shows the API caller rather than the integration connector''s system user, and (b) waits on availPackages.<PackageType> rather than just any package version, because MECM imports can produce a source-media zip well before any deployable type — calling Start-JuribaAppRSmokeTest before the matching availPackages flag flips true returns "CantFindTheAppInformation" (HTTP 400). The script now reports which package types ARE available if the requested one never materialises.

0.3.2 - Address PR review feedback. Remove-JuribaAppRMECMProvider: drop ConfirmImpact=High (which auto-prompted on -Id deletion too) for ConfirmImpact=Medium plus an explicit ShouldContinue gate on the -All branch — single-id removal now uses the regular Confirm flow, bulk removal still prompts unless -Confirm:$false. Get-JuribaAppRMECMImportAvailability: document the integer return value (0=unavailable, 1=ready) and add a guard-pattern example. Examples/Import-MECMAppAndSmokeTest.ps1: fix Watch-JuribaAppRApplicationStatus name split across two lines in the description.

0.3.1 - Fix the MECM import body shape and add the missing scan-list cmdlet. Reverse-engineered the AppR SPA''s Scan Import page (importSelectedApplications in chunk-46NRXZRT.js): the import API expects { filteringObjects: [{ id: <originalApplicationId>, model: <int> }] } where id is the CM-side string and model is mirrored verbatim from the scan-list row (typically 0 for an MECM Application). The previous Start-JuribaAppRMECMImport sent the AppR-side numeric id with model=1, which the server accepts with 200 OK but silently no-ops. New: Get-JuribaAppRMECMScanList (wraps GET /api/integration/{providerId}/scan/list — returns rows with originalApplicationId + model + status). Updated: Start-JuribaAppRMECMImport accepts pipeline input from Get-JuribaAppRMECMScanList and derives the body fields from each row; the FilteringObjects / Body parameter sets remain as escape hatches. Examples/Import-MECMAppAndSmokeTest.ps1 rewritten to use the scan-list lookup instead of -FilteringSccmId; -FilteringSccmId is replaced by -ImportEverything for the bulk case.

0.3.0 - Add MECM (SCCM) import + provider cmdlets covering /api/admin/sccm/*. New: Get-JuribaAppRMECMProvider (list configured integration providers — Intune + MECM — list or single by -Id), Get-JuribaAppRMECMImportAvailability (preflight), Get-JuribaAppRMECMImportEvent (event log), Start-JuribaAppRMECMImport (-FilteringObjects scopes which apps to import), Set-JuribaAppRMECMProviderUniqueness (toggle uniqueness on a provider), Remove-JuribaAppRMECMProvider (-Id or -All). Also adds Examples/Import-MECMAppAndSmokeTest.ps1 — end-to-end customer scenario: import a single CM app then run a smoke test against a chosen VM group.

0.2.0 - Add Get-JuribaAppRSession. Rename Get-JuribaAppRDefaultSettings -> Get-JuribaAppRDefaultSetting and Get-JuribaAppRTestStats -> Get-JuribaAppRTestStat (plural names kept as backward-compat aliases). Watch-* cmdlets now use Write-Progress + Write-Verbose for progress output. Raise minimum PowerShellVersion to 7.1 (required for Read-Host -MaskInput in example scripts). New interactive example scripts: Invoke-JuribaAppRSelfService.ps1 and Invoke-JuribaAppRSelfServiceWithTesting.ps1.'

        } # End of PSData hashtable

    } # End of PrivateData hashtable

}
