#
# Module manifest for module 'Juriba.AppR'
#
# Generated by: Juriba
#
# Generated on: 03/20/2026
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'Juriba.AppR.psm1'

    # Version number of this module.
    ModuleVersion     = '0.1.1'

    # Supported PSEditions
    CompatiblePSEditions = @('Core')

    # ID used to uniquely identify this module
    GUID              = 'a7e3f8b1-4d2c-4f6a-9e1b-3c5d7f8a2b4e'

    # Author of this module
    Author            = 'Juriba'

    # Company or vendor of this module
    CompanyName       = 'Juriba'

    # Copyright statement for this module
    Copyright         = '(c) Juriba. All rights reserved.'

    # Description of the functionality provided by this module
    Description       = 'PowerShell module to interact with Juriba App Readiness (AppR). Provides cmdlets for managing applications, packaging, smoke testing, quality review, and publishing to distribution systems such as Intune and MECM.'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '7.0'

    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        # Connection & Authentication
        "Connect-JuribaAppR",
        "Disconnect-JuribaAppR",
        "Get-JuribaAppRSession",
        "Set-JuribaAppRAPIKey",
        "Get-JuribaAppRAboutInfo",

        # Query - Applications
        "Get-JuribaAppRApplication",
        "Get-JuribaAppRApplicationList",
        "Get-JuribaAppRApplicationStatus",
        "Get-JuribaAppRApplicationPackage",
        "Get-JuribaAppRApplicationPackageDetail",
        "Get-JuribaAppRApplicationEvent",

        # Query - Users
        "Get-JuribaAppRUser",

        # Query - Quality Review
        "Get-JuribaAppRQualityReview",

        # Settings
        "Get-JuribaAppRDefaultSetting",
        "Get-JuribaAppRCommandSuggestion",

        # Upload / Create / Monitor Applications
        "Send-JuribaAppRSetupFile",
        "New-JuribaAppRApplication",
        "Get-JuribaAppRApplicationCreationState",
        "Watch-JuribaAppRApplicationCreation",
        "Watch-JuribaAppRApplicationStatus",
        "Set-JuribaAppRApplication",
        "Set-JuribaAppRApplicationOwner",
        "Set-JuribaAppRApplicationCommandLine",
        "Remove-JuribaAppRApplication",

        # Testing
        "Get-JuribaAppRVMGroup",
        "Get-JuribaAppRTestApplication",
        "Start-JuribaAppRSmokeTest",
        "Stop-JuribaAppRSmokeTest",
        "Get-JuribaAppRTestResult",
        "Get-JuribaAppRTestStat",

        # Publishing
        "Get-JuribaAppRIntegrationConnector",
        "Get-JuribaAppRPublishingProperty",
        "Invoke-JuribaAppRPublishIntune",
        "Invoke-JuribaAppRPublishMECM",
        "Invoke-JuribaAppRPublishGeneric",

        # Knowledge Base
        "Search-JuribaAppRKnowledgeBase",

        # Generic Integration (v1 API - refactored from original scripts)
        "Get-JuribaAppRGenericIntegration",
        "Get-JuribaAppRGenericIntegrationPublishing",
        "Get-JuribaAppRGenericIntegrationPrerequisite",
        "Get-JuribaAppRGenericIntegrationProperty",
        "Get-JuribaAppRGenericIntegrationSource",
        "Add-JuribaAppRGenericIntegrationLog",
        "Update-JuribaAppRGenericIntegrationPublishingState"
    )

    # Cmdlets to export from this module
    CmdletsToExport   = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module
    AliasesToExport   = @(
        "Connect-AppR",
        "Disconnect-AppR",
        # Backward-compatibility aliases for plural→singular renames (v0.1.x):
        "Get-JuribaAppRDefaultSettings",
        "Get-JuribaAppRTestStats"
    )

    # Private data to pass to the module specified in RootModule/ModuleToProcess.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('Juriba', 'AppReadiness', 'AppR', 'Packaging', 'Intune', 'MECM', 'SmokeTest')

            # A URL to the license for this module.
            LicenseUri = 'https://raw.githubusercontent.com/juribalimited/powershell-module-appr/main/LICENSE'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/juribalimited/powershell-module-appr'

            # A URL to an icon representing this module.
            IconUri    = 'https://raw.githubusercontent.com/juribalimited/powershell-module-appr/main/resources/juriba_logo.jpeg'

            # ReleaseNotes of this module
            ReleaseNotes = 'Initial release - Wave 1 cmdlets covering application management, smoke testing, publishing, and generic integration.'

        } # End of PSData hashtable

    } # End of PrivateData hashtable

}
